// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResourceManagerAPI.DBContext;

#nullable disable

namespace ResourceManagerAPI.Migrations
{
    [DbContext(typeof(PGDBContext))]
    [Migration("20230530081446_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourceManagerAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpID"));

                    b.Property<string>("EmailID")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text");

                    b.HasKey("EmpID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.EmployeeTasks", b =>
                {
                    b.Property<int>("EmployeeTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeTaskID"));

                    b.Property<int>("EmpID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Finish")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TaskName")
                        .HasColumnType("text");

                    b.HasKey("EmployeeTaskID");

                    b.ToTable("employeetasks");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.PlanUploadRecord", b =>
                {
                    b.Property<int>("UploadRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UploadRecordId"));

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UploadRecordId");

                    b.ToTable("uploadrecord");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.ResourceSkills", b =>
                {
                    b.Property<int>("ResourceSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResourceSkillID"));

                    b.Property<int>("ResourceID")
                        .HasColumnType("integer");

                    b.Property<int>("SkillSetID")
                        .HasColumnType("integer");

                    b.HasKey("ResourceSkillID");

                    b.ToTable("resourceskills");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.Resources", b =>
                {
                    b.Property<int>("ResourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResourceID"));

                    b.Property<string>("EmailID")
                        .HasColumnType("text");

                    b.Property<int>("EmpID")
                        .HasColumnType("integer");

                    b.HasKey("ResourceID");

                    b.ToTable("resources");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.SkillGroups", b =>
                {
                    b.Property<int>("SkillGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillGroupID"));

                    b.Property<string>("SkillGroup")
                        .HasColumnType("text");

                    b.HasKey("SkillGroupID");

                    b.ToTable("skillgroup");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.SkillSet", b =>
                {
                    b.Property<int>("SkillSetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillSetID"));

                    b.Property<int>("SkillGroupID")
                        .HasColumnType("integer");

                    b.Property<int>("SkillID")
                        .HasColumnType("integer");

                    b.HasKey("SkillSetID");

                    b.ToTable("skillset");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.Skills", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillID"));

                    b.Property<string>("Skill")
                        .HasColumnType("text");

                    b.HasKey("SkillID");

                    b.ToTable("skill");
                });

            modelBuilder.Entity("ResourceManagerAPI.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
